projeto/app/urls.py
from django.urls import path
from app.views import Index

app_name='app'
urlpatterns = [

    path('', Index.as_view(), name='index'),
    #path('cadastro', views.cadastro, name='cadastro')
]

projeto/projeto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

projeto/app/models.py
from django.db import models

# Create your models here.


class Gato(models.Model):
    nome = models.CharField(max_length=100, help_text='Nome do bixiro')
    tipos = models.TextField(max_length=255, help_text='Tipo do bixinho', null=True)




    def __str__(self):
        """String for representing the Model object."""
        return self.nome

projeto/pessoas/models.py
from django.db import models

# Create your models here.


class Pessoa(models.Model):
    nome = models.CharField(max_length=200)
    senha = models.IntegerField()

projeto/app/views.py
from django.shortcuts import render
from django.views.generic import ListView
from app.models import Gato


# Create your views here.



class Index(ListView):
    num_gatos = Gato.objects.all().count()
    model = Gato
    template_name = 'index.html'
    context_object_name = 'gatos'

    paginate_by = 2


def cadastro(request):
    num_gatos = Gato.objects.all().count()
    context = {
        'num_gatos': num_gatos
    }

    return render(request, 'cadastro.html')

projeto/pessoas/views.py
from django.shortcuts import render

# Create your views here.

projeto/app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/basic.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'vendor/jquery/jquery.js' %}"></script>
    <title>Document</title>
</head>
<body>
    {% include "topbar.html" %}


    {% block content %}

    {% endblock %}

    <script src="{% static 'vendor/bootstrap.js' %}"></script>
    <script>
        

        $(document).ready(function(){

            
            $('.navbar .btn').on('click', function(){
                $('#top-search').show(400)
            })


        })
    </script>
</body>
</html>

projeto/app/templates/cadastro.html
{% extends "base.html" %}


{% block content %}


    <h2>Cadastro de gatos!</h2>

{% endblock %}

projeto/app/templates/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}


    <div class="d-flex p-5 align-items-stretch justify-content-center cards-index">
        <a class="col-6 col-md-3 mr-5 p-0" href="#" id="caracter">
            <div class="card">
                <div class="card-title">
                    <p class="h4 text-center">
                        Escolha as caracteristicas
                    </p>
                </div>
                <img class="img-fluid" src="{% static 'img/gato.jpg' %}">
            </div>
        </a>
        <a class="col-6 col-md-3 ml-5 p-0" href="#" id="random">
            <div class="card">
                <div class="card-title">
                    <p class="h4 text-center">
                        Aleatório
                    </p>
                </div>
                <img class="img-fluid" src="{% static 'img/gato2.jpg' %}">
            </div>
        </a>
    </div>

    <div class="gatos-lista card">
        <h3 class="card-title display-5 px-3 py-2 rounded bg-primary text-white">Alguns gatinhos</h3>

        <div class="card-content">
            <div class="bg-grey d-flex justify-content-between px-3">
                <a class="btn btn-primary"> < </a>
                <p>Páginas: {{paginator.page_range}}</p>
                <a class="btn btn-primary" href="?page={{page_obj.next_page_number}}"> > </a>
                
            
            </div>

            
            
            {% if gatos %}
                
                {% for gato in gatos %}
                    <p class="h3 my-5 text-center">{{gato.nome}}</p>

                {% endfor %}

            {% else %}

            

            {% endif %}
        </div>
    </div>
    

{% endblock %}

projeto/app/templates/topbar.html
<header class="navbar shadow-sm px-3">
    <button class="navbar-toggler d-md-none">
        <i class="fa fa-menu"></i>
    </button>
    <a class="navbar-brand" href="{% url 'app:index' %}">
        <i class="fa fa-paw"></i> Adota!
    </a>
    <div class="col-6 ml-auto p-2 d-flex justify-content-end">
        
        <input class="w-100 collapse pl-2" id="top-search" placeholder="Ex.: Gato listrado">
        <button href="#" class="btn btn-search">
            <i class="fa fa-search text-primary"></i>
        </button>


    </div>
    

</header>